[package]
name = "cyndikator-dispatch"
version = "0.1.0"
authors = ["eulegang <eulegang@eulegang.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

derive_builder = "0.9"
nom = "6.1"
regex = "1"

